version = 1

test_patterns = [
  "**/*.spec.ts",
  "backend/src/test/**/*.java"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "browser",
    "jest"
  ]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"