version: '3'

services:

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data 777
    ports:
      - 5432:5432
    profiles:
      - dev
      - dev-be
      - ''

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - ./db-resources:/db-resources
      - ./uploads:/uploads
    ports:
      - 8080:8080
    profiles:
      - dev
      - dev-be
      - prod
      - ''

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - dev
      - prod
      - ''

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_UI_AUTH_FILE: /etc/.mailpitpsswd
      MP_SMTP_AUTH_FILE: /etc/.mailpitpsswd
    volumes:
      - ./.dev/.mailpitpsswd:/etc/.mailpitpsswd
    profiles:
      - dev
      - ''

  typesense:
    image: typesense/typesense:0.25.1
    container_name: typesense
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 8108:8108
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY}'
    profiles:
      - dev
      - prod
      - ''