version: '3'

services:

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APPLICATION_SERVER: ${APPLICATION_SERVER}
        DATABASE_SCHEMA_HANDLING_ON_STARTUP: ${DATABASE_SCHEMA_HANDLING_ON_STARTUP}
        DATABASE_SCHEMA_CREATE_TYPE: ${DATABASE_SCHEMA_CREATE_TYPE}
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - ./db-resources:/db-resources
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"

volumes:
  cms-db:
