version: '3'

services:

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data 777
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APPLICATION_SERVER: ${APPLICATION_SERVER}
        DATABASE_SCHEMA_HANDLING_ON_STARTUP: ${DATABASE_SCHEMA_HANDLING_ON_STARTUP}
        DATABASE_SCHEMA_CREATE_TYPE: ${DATABASE_SCHEMA_CREATE_TYPE}
        SMTP_SERVER: ${SMTP_SERVER}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USERNAME: ${SMTP_USERNAME}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - ./db-resources:/db-resources
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mailpit

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_UI_AUTH_FILE: /etc/.mailpitpsswd
      MP_SMTP_AUTH_FILE: /etc/.mailpitpsswd
    volumes:
      - ./.dev/.mailpitpsswd:/etc/.mailpitpsswd
