app:
  url: ${APP_URL:http://localhost}
  typesense:
    cache:
      enabled: ${TYPESENSE_CACHE_ENABLED:true}
      ttl: ${TYPESENSE_CACHE_TTL:60000}
    host: ${TYPESENSE_HOST:localhost}
    key: ${TYPESENSE_API_KEY:devapikey}
  path:
    backups: ${BACKUPS_DIRECTORY:/db-resources/}
    uploads: ${UPLOADS_DIRECTORY:/uploads/}
    templates: ${EMAIL_TEMPLATES_DIRECTORY:/emailTemplates/}
  database:
    schema:
      create-type: ${DATABASE_SCHEMA_CREATE_TYPE:populate}
      handling-on-startup: ${DATABASE_SCHEMA_HANDLING_ON_STARTUP:create}

---

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
      timeout: 30m

spring:
  data:
    web:
      pageable:
        default-page-size: 1000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    active: secured, postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./h2db;TRACE_LEVEL_FILE=0
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: h2

---

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: ${app.database.schema.handling-on-startup}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: postgres

---

springdoc:
  api-docs:
    enabled: true
    path: /api/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui

spring:
  mail:
    host: ${SMTP_SERVER:none}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:none}
    password: ${SMTP_PASSWORD:none}
    protocol: smtp
    properties.mail.smtp:
      auth: ${SMTP_USE_AUTH:true}
      starttls.enable: ${SMTP_USE_TLS:true}


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
